title: Women in STEM
author: Q
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Come and share your awesome ideas on how to keep women in STEM. All are welcome!
# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
